name: CI Python

on:
  push:
    branches: [main]
jobs:
  sast_scan:
    runs-on: [ubuntu-latest]
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8

      - name: Install Bandit
        run: |
          pip install bandit

      - name: Run Bandit Scan
        run: |
          bandit -r .
